import { StyleSheet } from "react-native";

import type { PeacePlotPalette } from "@/theme/peaceplot-theme";

export function createDiscoverItemStyles(c: PeacePlotPalette) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: "transparent" },
    backRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 4,
    },
    backLabel: { fontSize: 16, fontWeight: "600", color: c.primary },
    scroll: { flex: 1 },
    scrollContent: { paddingHorizontal: 20, paddingBottom: 120 },
    badgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 12 },
    pill: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.border,
    },
    pillText: { fontSize: 12, fontWeight: "600", color: c.textBody },
    title: { fontSize: 24, fontWeight: "800", color: c.text, marginBottom: 8, lineHeight: 30 },
    sub: { fontSize: 16, lineHeight: 24, color: c.textBody, marginBottom: 20 },
    mediaFrame: {
      height: 260,
      borderRadius: 12,
      overflow: "hidden",
      backgroundColor: c.surfaceDeep,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    mediaHint: { fontSize: 13, color: c.textMuted, paddingHorizontal: 14, textAlign: "center" },
    readerWrap: { width: "100%", height: "100%", paddingHorizontal: 12, paddingVertical: 10 },
    readerText: { color: c.text, fontSize: 15, lineHeight: 24 },
    primaryOpenBtn: {
      borderWidth: 1,
      borderColor: c.primary,
      backgroundColor: c.primary,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 9,
      marginBottom: 12,
      alignSelf: "flex-start",
    },
    primaryOpenBtnText: { color: c.textOnPrimary, fontSize: 13, fontWeight: "800" },
    actionRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
    actionBtn: {
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    actionBtnText: { color: c.text, fontSize: 12, fontWeight: "700" },
    card: {
      backgroundColor: c.card,
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 16,
    },
    cardTitle: { fontSize: 13, fontWeight: "800", color: c.textMuted, marginBottom: 8 },
    cardBody: { fontSize: 15, lineHeight: 22, color: c.textBody },
    disclaimer: { fontSize: 12, lineHeight: 18, color: c.textMuted, fontStyle: "italic" },
    notFound: { padding: 24 },
  });
}
